### PR TITLE
include dist builds in the repo proper

### PR DESCRIPTION
**Pull request by jab**
Should be more accessible than Release downloads.

ref: https://groups.google.com/d/topic/uproxy-eng/7AUGXiM_XL0/discussion

### CODE REVIEW

**Comment by agallant** [comment]
We may want to look into - https://help.github.com/articles/versioning-large-files/

GitHub does support checking in files up to 100MB directly like this, but has a soft quota limit around 1GB/repo so it may not be maintainable for many releases. Large File Storage would let us go further I assume, though we'd also need to doublecheck that it is accessible in various regions.

**Comment by jab** [comment]
Thanks @soycode! https://help.github.com/articles/versioning-large-files/ only mentions usefulness for overcoming the 100MB per-file quota (which we're currently not in danger of hitting). Do you know how it affects the soft 1GB-total-repo-history quota you mentioned?

At this rate, we would hit the 1 GB soft quota in about 7 releases (1GB / (45MB \* 3 files)). If LFS doesn't increase that quota, I can check in a script that rewrites the repo history to remove old build artifacts. If we continue to upload them to Releases, we can treat that as the canonical archive of old build artifacts.

In the interest of reducing unnecessary history bloat, does anyone know if there's a reason we're including the en-US .zip along with the .exe (see https://github.com/uProxy/uproxy-windows-installer/releases), but only the .exe for zh-CN? If we can get away with just the .exe's, I'll remove the .zip from this PR.

**Comment by agallant** [comment]
I think LFS still has a 1GB overall quota for free, but you can pay for additional storage ($5/month for 50GB of bandwidth/storage: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/). So, this can be a "cross-that-bridge-when-we-have-to" sort of thing - alternatively, just truncating old releases is reasonable.

**Comment by gwpenn** [comment]
The zip was included because a marketing page wanted to use bit.ly links, and that service gives warnings if users follow links to an .exe file. We only need the .exe's in this repo. Also, I don't think it would be immoral to just rewrite the git history and permanently delete old releases from the repo, when there are new ones. That would prevent us ever hitting the 1GB limit.

**Comment by jab** [comment]
Thanks @gwpenn! Rewriting repo history sounds good to me, but come to think of it, if we're going ahead with that, would it be better to have a separate, dedicated repo just for this, whose history we muck with as needed, to avoid messing with this repo's history? Alternatively we could just keep the build artifacts on a branch of this repo whose history we can mess with and just never merge that to master; the links will work just as well.

**Comment by jab** [comment]
Btw I updated the README with Download instructions as discussed earlier :)

**Comment by jab** [comment]
I went ahead and created an orphan `dist` branch (no history in common with `master`) with the build artifacts. We can rewrite history there as needed and never merge it, keeping it an isolated thing.

Superseded by: #4

**Pull request closed without merging**
