### PR TITLE
add download link to readme

### PR DESCRIPTION
**Pull request by jab**
This adds a download link to the README pointing to the new https://github.com/uProxy/uproxy-windows-installer/tree/dist#download-latest page.

### CODE REVIEW

**Comment by gwpenn** [comment]
Now that it's in a repository, I wonder if we still also want to publish the release? I think I would lean towards not doing that, since Chinese users might try downloading the release version and then get discouraged. If we're removing the binaries from releases, there's no need to include instructions for publishing the release. Other than that, LGTM.

**Comment by jab** [comment]
Thanks for reviewing and good point, @gwpenn. In case we do ever need to test an older release (exactly the file that was distributed, not a freshly-attempted replica), we could toss these in a Drive folder, or actually continue to use GitHub Release Downloads to keep it all in the same place, but put a big old download link in each release's description leading users to the right place, such as I just did here: https://github.com/uProxy/uproxy-windows-installer/releases

Happy to do either, lmk what you think!

**Comment by gwpenn** [comment]
Yeah, I think I would just keep it simple and store old releases our of the way, in drive. People never read things. ;)

**Comment by jab** [comment]
Sounds good. Created a folder in Drive and uploaded the v0.1.1 artifacts to it:
https://drive.google.com/drive/folders/0B22PfwRIULBDc1VicmpNVk5qWk0

Updated the README in 81d2ef1 with these latest instructions:
https://github.com/uProxy/uproxy-windows-installer/blob/81d2ef15917fb9a1815f6863e3cf326e9f86dd32/README.md#to-create-a-release

and... merged!

**Comment by jab** [comment]
Btw, I kept the instruction to add the download link to the release description because GitHub will still show a Downloads section even if we don't upload any binaries, just containing the source tarball and zipball. If a user does find herself there, hopefully that big CLICK HERE FOR THE DOWNLOAD PAGE will get her to the right place.

**Pull request merged**
